// 108 cards

const CardDeck = [
	{
		id: 1,
		value: "0",
		color: "red",
		src: "assets/cards-front/0R.png",
	},
	{
		id: 2,
		value: "1",
		color: "red",
		src: "assets/cards-front/1R.png",
	},
	{
		id: 3,
		value: "2",
		color: "red",
		src: "assets/cards-front/2R.png",
	},
	{
		id: 4,
		value: "3",
		color: "red",
		src: "assets/cards-front/3R.png",
	},
	{
		id: 5,
		value: "4",
		color: "red",
		src: "assets/cards-front/4R.png",
	},
	{
		id: 6,
		value: "5",
		color: "red",
		src: "assets/cards-front/5R.png",
	},
	{
		id: 7,
		value: "6",
		color: "red",
		src: "assets/cards-front/6R.png",
	},
	{
		id: 8,
		value: "7",
		color: "red",
		src: "assets/cards-front/7R.png",
	},
	{
		id: 9,
		value: "8",
		color: "red",
		src: "assets/cards-front/8R.png",
	},
	{
		id: 10,
		value: "9",
		color: "red",
		src: "assets/cards-front/9R.png",
	},
	{
		id: 11,
		value: "1",
		color: "red",
		src: "assets/cards-front/1R.png",
	},
	{
		id: 12,
		value: "2",
		color: "red",
		src: "assets/cards-front/2R.png",
	},
	{
		id: 13,
		value: "3",
		color: "red",
		src: "assets/cards-front/3R.png",
	},
	{
		id: 14,
		value: "4",
		color: "red",
		src: "assets/cards-front/4R.png",
	},
	{
		id: 15,
		value: "5",
		color: "red",
		src: "assets/cards-front/5R.png",
	},
	{
		id: 16,
		value: "6",
		color: "red",
		src: "assets/cards-front/6R.png",
	},
	{
		id: 17,
		value: "7",
		color: "red",
		src: "assets/cards-front/7R.png",
	},
	{
		id: 18,
		value: "8",
		color: "red",
		src: "assets/cards-front/8R.png",
	},
	{
		id: 19,
		value: "9",
		color: "red",
		src: "assets/cards-front/9R.png",
	},
	{
		id: 20,
		value: "skip",
		color: "red",
		src: "assets/cards-front/skipR.png",
	},
	{
		id: 21,
		value: "skip",
		color: "red",
		src: "assets/cards-front/skipR.png",
	},
	{
		id: 22,
		value: "plus2",
		color: "red",
		src: "assets/cards-front/D2R.png",
	},
	{
		id: 23,
		value: "plus2",
		color: "red",
		src: "assets/cards-front/D2R.png",
	},
	{
		id: 24,
		value: "reverse",
		color: "red",
		src: "assets/cards-front/_R.png",
	},
	{
		id: 25,
		value: "reverse",
		color: "red",
		src: "assets/cards-front/_R.png",
	},
	{
		id: 26,
		value: "0",
		color: "yellow",
		src: "assets/cards-front/0Y.png",
	},
	{
		id: 27,
		value: "1",
		color: "yellow",
		src: "assets/cards-front/1Y.png",
	},
	{
		id: 28,
		value: "2",
		color: "yellow",
		src: "assets/cards-front/2Y.png",
	},
	{
		id: 29,
		value: "3",
		color: "yellow",
		src: "assets/cards-front/3Y.png",
	},
	{
		id: 30,
		value: "4",
		color: "yellow",
		src: "assets/cards-front/4Y.png",
	},
	{
		id: 31,
		value: "5",
		color: "yellow",
		src: "assets/cards-front/5Y.png",
	},
	{
		id: 32,
		value: "6",
		color: "yellow",
		src: "assets/cards-front/6Y.png",
	},
	{
		id: 33,
		value: "7",
		color: "yellow",
		src: "assets/cards-front/7Y.png",
	},
	{
		id: 34,
		value: "8",
		color: "yellow",
		src: "assets/cards-front/8Y.png",
	},
	{
		id: 35,
		value: "9",
		color: "yellow",
		src: "assets/cards-front/9Y.png",
	},
	{
		id: 36,
		value: "1",
		color: "yellow",
		src: "assets/cards-front/1Y.png",
	},
	{
		id: 37,
		value: "2",
		color: "yellow",
		src: "assets/cards-front/2Y.png",
	},
	{
		id: 38,
		value: "3",
		color: "yellow",
		src: "assets/cards-front/3Y.png",
	},
	{
		id: 39,
		value: "4",
		color: "yellow",
		src: "assets/cards-front/4Y.png",
	},
	{
		id: 40,
		value: "5",
		color: "yellow",
		src: "assets/cards-front/5Y.png",
	},
	{
		id: 41,
		value: "6",
		color: "yellow",
		src: "assets/cards-front/6Y.png",
	},
	{
		id: 42,
		value: "7",
		color: "yellow",
		src: "assets/cards-front/7Y.png",
	},
	{
		id: 43,
		value: "8",
		color: "yellow",
		src: "assets/cards-front/8Y.png",
	},
	{
		id: 44,
		value: "9",
		color: "yellow",
		src: "assets/cards-front/9Y.png",
	},
	{
		id: 45,
		value: "skip",
		color: "yellow",
		src: "assets/cards-front/skipY.png",
	},
	{
		id: 46,
		value: "skip",
		color: "yellow",
		src: "assets/cards-front/skipY.png",
	},
	{
		id: 47,

		value: "plus2",
		color: "yellow",

		src: "assets/cards-front/D2Y.png",
	},

	{
		id: 48,

		value: "plus2",
		color: "yellow",

		src: "assets/cards-front/D2Y.png",
	},

	{
		id: 49,

		value: "reverse",
		color: "yellow",

		src: "assets/cards-front/_Y.png",
	},

	{
		id: 50,

		value: "reverse",
		color: "yellow",

		src: "assets/cards-front/_Y.png",
	},
	{
		id: 51,
		value: "0",
		color: "blue",
		src: "assets/cards-front/0B.png",
	},
	{
		id: 52,
		value: "1",
		color: "blue",
		src: "assets/cards-front/1B.png",
	},
	{
		id: 53,
		value: "2",
		color: "blue",
		src: "assets/cards-front/2B.png",
	},
	{
		id: 54,
		value: "3",
		color: "blue",
		src: "assets/cards-front/3B.png",
	},
	{
		id: 55,
		value: "4",
		color: "blue",
		src: "assets/cards-front/4B.png",
	},
	{
		id: 56,
		value: "5",
		color: "blue",
		src: "assets/cards-front/5B.png",
	},
	{
		id: 57,
		value: "6",
		color: "blue",
		src: "assets/cards-front/6B.png",
	},
	{
		id: 58,
		value: "7",
		color: "blue",
		src: "assets/cards-front/7B.png",
	},
	{
		id: 59,
		value: "8",
		color: "blue",
		src: "assets/cards-front/8B.png",
	},
	{
		id: 60,
		value: "9",
		color: "blue",
		src: "assets/cards-front/9B.png",
	},
	{
		id: 61,
		value: "1",
		color: "blue",
		src: "assets/cards-front/1B.png",
	},
	{
		id: 62,
		value: "2",
		color: "blue",
		src: "assets/cards-front/2B.png",
	},
	{
		id: 63,
		value: "3",
		color: "blue",
		src: "assets/cards-front/3B.png",
	},
	{
		id: 64,
		value: "4",
		color: "blue",
		src: "assets/cards-front/4B.png",
	},
	{
		id: 65,
		value: "5",
		color: "blue",
		src: "assets/cards-front/5B.png",
	},
	{
		id: 66,
		value: "6",
		color: "blue",
		src: "assets/cards-front/6B.png",
	},
	{
		id: 67,
		value: "7",
		color: "blue",
		src: "assets/cards-front/7B.png",
	},
	{
		id: 68,
		value: "8",
		color: "blue",
		src: "assets/cards-front/8B.png",
	},
	{
		id: 69,
		value: "9",
		color: "blue",
		src: "assets/cards-front/9B.png",
	},
	{
		id: 70,
		value: "skip",
		color: "blue",
		src: "assets/cards-front/skipB.png",
	},
	{
		id: 71,
		value: "skip",
		color: "blue",
		src: "assets/cards-front/skipB.png",
	},
	{
		id: 72,
		value: "plus2",
		color: "blue",
		src: "assets/cards-front/D2B.png",
	},
	{
		id: 73,
		value: "plus2",
		color: "blue",
		src: "assets/cards-front/D2B.png",
	},
	{
		id: 74,
		value: "reverse",
		color: "blue",
		src: "assets/cards-front/_B.png",
	},
	{
		id: 75,
		value: "reverse",
		color: "blue",
		src: "assets/cards-front/_B.png",
	},
	{
		id: 76,
		value: "0",
		color: "green",
		src: "assets/cards-front/0G.png",
	},
	{
		id: 77,
		value: "1",
		color: "green",
		src: "assets/cards-front/1G.png",
	},
	{
		id: 78,
		value: "2",
		color: "green",
		src: "assets/cards-front/2G.png",
	},
	{
		id: 79,
		value: "3",
		color: "green",
		src: "assets/cards-front/3G.png",
	},
	{
		id: 80,
		value: "4",
		color: "green",
		src: "assets/cards-front/4G.png",
	},
	{
		id: 81,
		value: "5",
		color: "green",
		src: "assets/cards-front/5G.png",
	},
	{
		id: 82,
		value: "6",
		color: "green",
		src: "assets/cards-front/6G.png",
	},
	{
		id: 83,
		value: "7",
		color: "green",
		src: "assets/cards-front/7G.png",
	},
	{
		id: 84,
		value: "8",
		color: "green",
		src: "assets/cards-front/8G.png",
	},
	{
		id: 85,
		value: "9",
		color: "green",
		src: "assets/cards-front/9G.png",
	},
	{
		id: 86,
		value: "1",
		color: "green",
		src: "assets/cards-front/1G.png",
	},
	{
		id: 87,
		value: "2",
		color: "green",
		src: "assets/cards-front/2G.png",
	},
	{
		id: 88,
		value: "3",
		color: "green",
		src: "assets/cards-front/3G.png",
	},
	{
		id: 89,
		value: "4",
		color: "green",
		src: "assets/cards-front/4G.png",
	},
	{
		id: 90,
		value: "5",
		color: "green",
		src: "assets/cards-front/5G.png",
	},
	{
		id: 91,
		value: "6",
		color: "green",
		src: "assets/cards-front/6G.png",
	},
	{
		id: 92,
		value: "7",
		color: "green",
		src: "assets/cards-front/7G.png",
	},
	{
		id: 93,
		value: "8",
		color: "green",
		src: "assets/cards-front/8G.png",
	},
	{
		id: 94,
		value: "9",
		color: "green",
		src: "assets/cards-front/9G.png",
	},
	// {
	// 	id: 95,
	// 	value: "skip",
	// 	color: "green",
	// 	src: "assets/cards-front/skipG.png",
	// },
	// {
	// 	id: 96,
	// 	value: "skip",
	// 	color: "green",
	// 	src: "assets/cards-front/skipG.png",
	// },
	// {
	// 	id: 97,
	// 	value: "plus2",
	// 	color: "green",
	// 	src: "assets/cards-front/D2G.png",
	// },
	// {
	// 	id: 98,
	// 	value: "plus2",
	// 	color: "green",
	// 	src: "assets/cards-front/D2G.png",
	// },
	// {
	// 	id: 99,
	// 	value: "reverse",
	// 	color: "green",
	// 	src: "assets/cards-front/_G.png",
	// },
	// {
	// 	id: 100,
	// 	value: "reverse",
	// 	color: "green",
	// 	src: "assets/cards-front/_G.png",
	// },
	// {
	// 	id: 101,
	// 	value: "wilde",
	// 	color: "none",
	// 	src: "assets/cards-front/W.png",
	// },
	// {
	// 	id: 102,
	// 	value: "wilde",
	// 	color: "none",
	// 	src: "assets/cards-front/W.png",
	// },
	// {
	// 	id: 103,
	// 	value: "wilde",
	// 	color: "none",
	// 	src: "assets/cards-front/W.png",
	// },
	// {
	// 	id: 104,
	// 	value: "wilde",
	// 	color: "none",
	// 	src: "assets/cards-front/W.png",
	// },
	// {
	// 	id: 105,
	// 	value: "plus4",
	// 	color: "none",
	// 	src: "assets/cards-front/D4W.png",
	// },
	// {
	// 	id: 106,
	// 	value: "plus4",
	// 	color: "none",
	// 	src: "assets/cards-front/D4W.png",
	// },
	// {
	// 	id: 107,
	// 	value: "plus4",
	// 	color: "none",
	// 	src: "assets/cards-front/D4W.png",
	// },
	// {
	// 	id: 108,
	// 	value: "plus4",
	// 	color: "none",
	// 	src: "assets/cards-front/D4W.png",
	// },
];

export default CardDeck;
